version: '3'

services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: matheusafonsouza/nginx
    container_name: nginx
    ports:
      - '80:80'
    networks:
      - prod-network
    depends_on:
      - node1
      - node2
      - node3

  mongodb:
    image: mongo
    container_name: mongo
    networks:
      - prod-network

  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: matheusafonsouza/alura-books
    container_name: alura-books1
    ports:
      - '3000'
    networks:
      - prod-network
    depends_on:
      - mongodb

  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: matheusafonsouza/alura-books
    container_name: alura-books2
    ports:
      - '3000'
    networks:
      - prod-network
    depends_on:
      - mongodb

  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: matheusafonsouza/alura-books
    container_name: alura-books3
    ports:
      - '3000'
    networks:
      - prod-network
    depends_on:
      - mongodb

networks:
  prod-network:
    driver: bridge
